/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.parqueo;

/**
 *
 * @author Shily
 */

import paquete1.*; // tus modelos: Persona, Vehiculo, Area, Ticket, Tarifa, Spot...
// si Parqueo lo tienes en ese paquete
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JComboBox;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;


public class Interfaz extends javax.swing.JFrame {
    
private Parqueo parqueo;
private DefaultTableModel ticketModel;
private DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");
    
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        parqueo = new Parqueo();

// Obtener el model de la tabla (asegúrate que tablaTickets es el nombre del JTable)
ticketModel = (DefaultTableModel) tablaTickets.getModel();

// Configurar combo boxes si no las llenaste en Design
if (cbTipoUsuario.getItemCount() == 0) {
    cbTipoUsuario.addItem("ESTUDIANTE");
    cbTipoUsuario.addItem("CATEDRATICO");
}
if (cbTipoVehiculo.getItemCount() == 0) {
    cbTipoVehiculo.addItem("AUTO");
    cbTipoVehiculo.addItem("MOTO");
}

// Opcional: centrar la ventana
this.setLocationRelativeTo(null);

refrescarTabla();
       

    }
    
    private void actualizarSpots() {
    int disponibles = parqueo.getTotalSpotsDisponibles();
    lblSpots.setText("Spots disponibles: " + disponibles);
}
    
    
    private String[] pedirDatosDePagoYTarifa() {

    // Combos
    JComboBox<String> cbMetodo = new JComboBox<>(new String[]{"EFECTIVO", "TARJETA", "SALDO"});
    JComboBox<String> cbTarifa = new JComboBox<>(new String[]{"VARIABLE", "FLAT"});

    // Panel
    JPanel panel = new JPanel();
    panel.setLayout(new java.awt.GridLayout(0, 1, 5, 5));

    panel.add(new JLabel("Seleccione método de pago:"));
    panel.add(cbMetodo);

    panel.add(new JLabel("Seleccione tipo de tarifa:"));
    panel.add(cbTarifa);

    int res = JOptionPane.showConfirmDialog(
            this,
            panel,
            "Datos de Pago y Tarifa",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
    );

    if (res == JOptionPane.OK_OPTION) {
        return new String[]{
            (String) cbMetodo.getSelectedItem(),
            (String) cbTarifa.getSelectedItem()
        };
    }

    return null; // cancelado
}
    
    private void refrescarTabla() {
    ticketModel.setRowCount(0); // limpiar filas
    for (Ticket t : parqueo.getListaTickets()) {
        String ingreso = (t.getFechaIngreso() != null) ? t.getFechaIngreso().format(dtf) : "";
        String salida = (t.getFechaSalida() != null) ? t.getFechaSalida().format(dtf) : "";
        String areaNombre = (t.getArea() != null) ? t.getArea().getNombre() : "";
        String spotId = (t.getSpot() != null) ? t.getSpot().getIdSpot() : "";
        String placa = (t.getVehiculo() != null) ? t.getVehiculo().getPlaca() : "";

        ticketModel.addRow(new Object[]{
            t.getIdTicket(), // o t.getId() según tu clase
            placa,
            areaNombre,
            spotId,
            ingreso,
            salida,
            t.getMonto(),
            t.getEstado()
        });
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        lblCarnet = new javax.swing.JLabel();
        tfCarnet = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        cbTipoUsuario = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbTipoVehiculo = new javax.swing.JComboBox<>();
        btnRegistrarRapido = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnEntrada = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblSpots = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        scrollTickets = new javax.swing.JScrollPane();
        tablaTickets = new javax.swing.JTable();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Parqueo UMG Mazatenango");
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        lblPlaca.setText("Placa");

        tfPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPlacaActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        lblTipoUsuario.setText("Tipo de Usuario");

        lblCarnet.setText("Carnet");

        tfCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCarnetActionPerformed(evt);
            }
        });

        cbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTE", "CATEDRATICO" }));
        cbTipoUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoUsuarioItemStateChanged(evt);
            }
        });
        cbTipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo Vehiculo");

        cbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Moto" }));
        cbTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoVehiculoActionPerformed(evt);
            }
        });

        btnRegistrarRapido.setText("Registrar (rápido)");
        btnRegistrarRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarRapidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(lblPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCarnet)
                            .addComponent(lblTipoUsuario))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(147, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnRegistrarRapido, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(tfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoUsuario)
                    .addComponent(cbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblCarnet)
                    .addComponent(tfCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarRapido))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnEntrada.setText("Registrar Entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnSalida.setText("Registrar Salida");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        btnRefrescar.setText("Refrescar Tickets");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblSpots.setText("Spots disponibles: --");

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCargar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEntrada)
                        .addGap(30, 30, 30)
                        .addComponent(btnSalida)
                        .addGap(26, 26, 26)
                        .addComponent(btnRefrescar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)))
                .addGap(45, 45, 45)
                .addComponent(lblSpots)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnCargar)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrada)
                    .addComponent(btnSalida)
                    .addComponent(btnRefrescar)
                    .addComponent(btnGuardar)
                    .addComponent(lblSpots))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        tablaTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Área", "Spot", "Ingreso", "Salida", "Monto", "Estado"
            }
        ));
        scrollTickets.setViewportView(tablaTickets);

        lblStatus.setText("\"\"");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 57, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollTickets))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(lblStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTickets, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStatus)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPlacaActionPerformed

    private void tfCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCarnetActionPerformed

    private void cbTipoUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoUsuarioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoUsuarioItemStateChanged

    private void btnRegistrarRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarRapidoActionPerformed

    String[] datos = pedirDatosDePagoYTarifa();
if (datos == null) {
    lblStatus.setText("Registro cancelado.");
    return;
}

String metodoPago = datos[0];
String tipoTarifa = datos[1];
        
    String placa = tfPlaca.getText().trim();
    String nombre = tfNombre.getText().trim();
    String carnet = tfCarnet.getText().trim();
    String tipoUsuario = (String) cbTipoUsuario.getSelectedItem();
    String tipoVeh = (String) cbTipoVehiculo.getSelectedItem();

    if (placa.isEmpty() || nombre.isEmpty()) {
        lblStatus.setText("Placa y nombre son obligatorios.");
        JOptionPane.showMessageDialog(this, "Complete la placa y el nombre.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Persona p = new Persona((int)(Math.random() * 100000), nombre, carnet, tipoUsuario);
    Tarifa tarifa;
if(tipoTarifa.equals("FLAT")){
    tarifa = new Tarifa(2, "FLAT", 10.0, 0.0, 0.0);
} else {
    tarifa = new Tarifa(1, "VARIABLE", 0.0, 5.0, 0.0);
}

    boolean ok = parqueo.registrarEntrada(placa, tipoVeh, p, tarifa);
    if (ok) {
        lblStatus.setText("Entrada registrada para placa " + placa);
    } else {
        lblStatus.setText("No hay espacio disponible.");
    }

    refrescarTabla();
    
    tfPlaca.setText("");
    tfNombre.setText("");
    tfCarnet.setText("");
    cbTipoUsuario.setSelectedIndex(0);
    cbTipoVehiculo.setSelectedIndex(0);
        
        actualizarSpots();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarRapidoActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed

    String placa = JOptionPane.showInputDialog(this, "Ingrese placa del vehículo:");
    if (placa == null) return;
    placa = placa.trim();
    if (placa.isEmpty()) {
        lblStatus.setText("Placa vacía.");
        return;
    }

    // 2. Intentar reingreso FLAT sin volver a cobrar
    boolean reingresoGratis = parqueo.intentarReingresoFlat(placa);
    if (reingresoGratis) {
        lblStatus.setText("Reingreso FLAT sin cobro para placa " + placa);
        refrescarTabla();
        return;   // MUY IMPORTANTE: aquí terminamos, no pedimos método de pago
    }

    // 3. Si no aplica reingreso gratis, ahora sí pedimos método de pago + tarifa
    String[] datos = pedirDatosDePagoYTarifa();
    if (datos == null) {
        lblStatus.setText("Registro cancelado.");
        return;
    }

    String metodoPago = datos[0];
    String tipoTarifa = datos[1];

    // 4. Crear Tarifa según lo seleccionado
    Tarifa tarifa;
    if ("FLAT".equalsIgnoreCase(tipoTarifa)) {
        tarifa = new Tarifa(2, "FLAT", 10.0, 0.0, 0.0);   // Q10 todo el día
    } else {
        tarifa = new Tarifa(1, "VARIABLE", 0.0, 5.0, 0.0); // Q5 por hora
    }

    // 5. Registrar entrada recurrente (aquí sí paga de nuevo)
    boolean ok = parqueo.registrarEntradaRecurrentePorPlaca(placa, tarifa);

    if (ok) {
        lblStatus.setText("Reingreso registrado. Placa: " + placa +
                          " - Pago: " + metodoPago +
                          " - Tarifa: " + tipoTarifa);
        refrescarTabla();
    } else {
        lblStatus.setText("No se encontró vehículo registrado con placa " + placa +
                          " o no hay espacio disponible.");
    }
actualizarSpots();


        // TODO add your handling code here:
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed

String placa = JOptionPane.showInputDialog(this, "Ingrese placa para registrar salida:");
    if (placa == null) return;
    placa = placa.trim();
    if (placa.isEmpty()) {
        lblStatus.setText("Placa vacía.");
        return;
    }

    boolean ok = parqueo.registrarSalida(placa);
    if (ok) {
        lblStatus.setText("Salida registrada para " + placa);
    } else {
        lblStatus.setText("No se encontró ticket activo para " + placa);
    }
    refrescarTabla();
    
    actualizarSpots();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed

     refrescarTabla();
    lblStatus.setText("Tabla actualizada.");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Guardar tickets como CSV");
    int opcion = chooser.showSaveDialog(this);

    if (opcion != JFileChooser.APPROVE_OPTION) {
        lblStatus.setText("Guardado cancelado.");
        return;
    }

    File archivo = chooser.getSelectedFile();
   
    if (!archivo.getName().toLowerCase().endsWith(".csv")) {
        archivo = new File(archivo.getParentFile(), archivo.getName() + ".csv");
    }

    
    try (PrintWriter out = new PrintWriter(new FileWriter(archivo))) {

       
        out.println("ID,Placa,Area,Spot,Ingreso,Salida,Monto,Estado");

        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

        for (Ticket t : parqueo.getListaTickets()) {
            String id = t.getIdTicket();
            String placa = t.getVehiculo() != null ? t.getVehiculo().getPlaca() : "";
            String area = t.getArea() != null ? t.getArea().getNombre() : "";
            String spot = t.getSpot() != null ? t.getSpot().getIdSpot() : "";
            String ingreso = (t.getFechaIngreso() != null) ? t.getFechaIngreso().format(dtf) : "";
            String salida = (t.getFechaSalida() != null) ? t.getFechaSalida().format(dtf) : "";
            double monto = t.getMonto();
            String estado = t.getEstado();

           
            out.printf("%s,%s,%s,%s,%s,%s,%.2f,%s%n",
                    id, placa, area, spot, ingreso, salida, monto, estado);
        }

        lblStatus.setText("Tickets guardados en: " + archivo.getAbsolutePath());

    } catch (IOException ex) {
        lblStatus.setText("Error al guardar CSV: " + ex.getMessage());
        JOptionPane.showMessageDialog(this,
                "Ocurrió un error al guardar el archivo:\n" + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
        
lblStatus.setText("Guardado (si la persistencia está implementada).");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cbTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoUsuarioActionPerformed

    private void cbTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoVehiculoActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed

 JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Cargar tickets desde CSV");
    int opcion = chooser.showOpenDialog(this);

    if (opcion != JFileChooser.APPROVE_OPTION) {
        lblStatus.setText("Carga cancelada.");
        return;
    }

    File archivo = chooser.getSelectedFile();

    try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {

        // 1. Limpiar la tabla actual
        ticketModel.setRowCount(0);

        // 2. Leer primera línea (encabezado) y descartarla
        String linea = br.readLine(); // encabezado: ID,Placa,...

        // 3. Leer cada línea de datos
        while ((linea = br.readLine()) != null) {
            if (linea.trim().isEmpty()) continue;

            // Separar por coma
            String[] parts = linea.split(",", -1); // -1 para conservar campos vacíos

            if (parts.length < 8) {
                continue; // línea incompleta, la ignoramos
            }

            String id      = parts[0];
            String placa   = parts[1];
            String area    = parts[2];
            String spot    = parts[3];
            String ingreso = parts[4];
            String salida  = parts[5];
            double monto   = 0.0;
            try {
                monto = Double.parseDouble(parts[6]);
            } catch (NumberFormatException ex) {
                monto = 0.0;
            }
            String estado  = parts[7];

            // Agregar fila a la tabla
            ticketModel.addRow(new Object[]{
                id, placa, area, spot, ingreso, salida, monto, estado
            });
        }

        lblStatus.setText("CSV cargado: " + archivo.getName());

    } catch (IOException ex) {
        lblStatus.setText("Error al cargar CSV: " + ex.getMessage());
        JOptionPane.showMessageDialog(this,
                "Ocurrió un error al leer el archivo:\n" + ex.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interfaz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnRegistrarRapido;
    private javax.swing.JButton btnSalida;
    private javax.swing.JComboBox<String> cbTipoUsuario;
    private javax.swing.JComboBox<String> cbTipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCarnet;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblSpots;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JScrollPane scrollTickets;
    private javax.swing.JTable tablaTickets;
    private javax.swing.JTextField tfCarnet;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPlaca;
    // End of variables declaration//GEN-END:variables
}
